menu:
  æ–‡ç« :
    å½’æ¡£: /archives/ || anzhiyu-icon-box-archive
    åˆ†ç±»: /categories/ || anzhiyu-icon-shapes
    æ ‡ç­¾: /tags/ || anzhiyu-icon-tags

  æˆ‘çš„:
    è¿½ç•ªé¡µ: /bangumis/ || anzhiyu-icon-bilibili
    ç›¸å†Œé›†: /album/ || anzhiyu-icon-images
    å·¥å…·é¡µ: /tools/ || anzhiyu-icon-thumbtack

  å…³äº:
    å…³äºæˆ‘: /about/ || anzhiyu-icon-paper-plane
    æ—¶å…‰æœº: /essay/ || anzhiyu-icon-lightbulb
    éšç§æ”¿ç­–: /privacy/ || anzhiyu-icon-copyright
    # éšä¾¿é€›é€›: javascript:toRandomPost() || anzhiyu-icon-shoe-prints1
# navç›¸å…³é…ç½®
nav:
  enable: true
  travelling: true # éšæœºåšå®¢
  clock: false # å¤©æ°”å·²å¤±æ•ˆ
  menu:
    - title: ä¸»é¡µ
      item:
        - name: ä¸»é¡µ
          link: http://yangjie.site/
          icon: /img/512.png
    - title: é¡¹ç›®
      item:
        - name: å°æ°å¯¼èˆª
          link: https://nav.yangjie.site/
          icon: /img/512.png
highlight_theme: pale night
highlight_copy: true
highlight_shrink: false
# ç¤¾äº¤å›¾æ ‡
# social settings (ç¤¾äº¤å›¾æ ‡è®¾ç½®)
social:
  Github: https://github.com/jiege6919 || anzhiyu-icon-github
  BiliBili: https://space.bilibili.com/646325099 || anzhiyu-icon-bilibili
# ä½œè€…å¡ç‰‡ çŠ¶æ€
# Avatar (å¤´åƒ)
avatar:
  img: /img/avatar.jpg

author_status:
  enable: true
  # å¯ä»¥æ˜¯ä»»ä½•å›¾ç‰‡ï¼Œå»ºè®®æ”¾è¡¨æƒ…åŒ…æˆ–è€…emojiå›¾ç‰‡ï¼Œæ•ˆæœéƒ½å¾ˆå¥½ï¼Œ[è¡¨æƒ…åŒ…é€ŸæŸ¥](https://emotion.xiaokang.me/)
  statusImg: "/img/about/logo.png"
  skills:
    - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
    - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
    - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
    - ğŸ”¨ è®¾è®¡å¼€å‘ä¸€æ¡é¾™
    - ğŸ¤ ä¸“ä¿®äº¤äº’ä¸è®¾è®¡
    - ğŸƒ è„šè¸å®åœ°è¡ŒåŠ¨æ´¾
    - ğŸ§± å›¢é˜Ÿå°ç»„å‘åŠ¨æœº
    - ğŸ’¢ å£®æ±‰äººç‹ è¯ä¸å¤š

# é¡¶éƒ¨å›¾
# default_top_img: /img/default.webp

# é¦–é¡µæ–‡ç«  meta æ˜¾ç¤º
post_meta:
  page:
    date_type: created # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: simple # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­— ==> å°±æ˜¯`å‘è¡¨äº`è¿™å‡ ä¸ªå­—
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: simple # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: false # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

# æ‰“èµ
reward:
  enable: true
  coinAudio: https://npm.elemecdn.com/akilar-candyassets@1.0.36/audio/aowu.m4a
  QR_code:
    - img: /img/wxpay.png
      link:
      text: å¾®ä¿¡
    - img: /img/Alipay.png
      link:
      text: æ”¯ä»˜å®

# æ–‡ç« ç›®å½• TOC
toc:
  post: true
  page: true
  number: true
  expand: false
  style_simple: false # for post

# ç›¸å…³æ–‡ç« 
related_post:
  enable: false
  limit: 3 # æ˜¾ç¤ºæ¨èæ–‡ç« æ•°ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸæ˜¾ç¤ºåˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥
# é¡µè„šè®¾ç½®
# --------------------------------------
footer:
  owner:
    enable: true
    since: 2019
  custom_text:
  runtime:
    enable: false
    launch_time: 10/13/2023 17:00:00 # ç½‘ç«™ä¸Šçº¿æ—¶é—´
    work_img:
    work_description:
    offduty_img:
    offduty_description:
  footerBar:
    enable: true
    authorLink: /
    cc:
      enable: true
      link: https://creativecommons.org/licenses/by-nc-sa/4.0/
    linkList:
      - link: https://beian.miit.gov.cn/
        text: èœ€ICPå¤‡2021020461å·-2
# é˜…è¯»æ¨¡å¼
readmode: true

# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true
  exclude:
    - /music/
    - /no-pjax/

# é¦–é¡µéšä¾¿é€›é€›peopleæ¨¡å¼ è€ŒéæŠ€èƒ½ç‚¹æ¨¡å¼ï¼Œå…³é—­åä¸ºæŠ€èƒ½ç‚¹æ¨¡å¼éœ€è¦é…ç½®creativity.yml
peoplecanvas:
  enable: false
  img: 

# æ¬¢è¿è¯­é…ç½®
greetingBox:
  enable: true # å¼€å¯åå¿…é¡»é…ç½®ä¸‹é¢çš„listå¯¹åº”çš„æ—¶é—´æ®µï¼Œä¸ç„¶ä¼šå‡ºç°å°ç™½æ¡
  default: æ™šä¸Šå¥½ğŸ‘‹
  list:
    - greeting: æ™šå®‰ğŸ˜´
      startTime: 0
      endTime: 5
    - greeting: æ—©ä¸Šå¥½é¸­ğŸ‘‹, ç¥ä½ ä¸€å¤©å¥½å¿ƒæƒ…ï¼
      startTime: 6
      endTime: 9
    - greeting: ä¸Šåˆå¥½ğŸ‘‹, çŠ¶æ€å¾ˆå¥½ï¼Œé¼“åŠ±ä¸€ä¸‹ï½
      startTime: 10
      endTime: 10
    - greeting: 11ç‚¹å¤šå•¦, åœ¨åšæŒä¸€ä¸‹å°±åƒé¥­å•¦ï½
      startTime: 11
      endTime: 11
    - greeting: åˆå®‰ğŸ‘‹, å®è´
      startTime: 12
      endTime: 14
    - greeting: ğŸŒˆå……å®çš„ä¸€å¤©è¾›è‹¦å•¦ï¼
      startTime: 14
      endTime: 18
    - greeting: 19ç‚¹å–½, å¥–åŠ±ä¸€é¡¿ä¸°ç››çš„å¤§é¤å§ğŸ”ã€‚
      startTime: 19
      endTime: 19
    - greeting: æ™šä¸Šå¥½ğŸ‘‹, åœ¨å±äºè‡ªå·±çš„æ—¶é—´å¥½å¥½æ”¾æ¾ğŸ˜Œ~
      startTime: 20
      endTime: 24

# å³é”®èœå•
rightClickMenu:
  enable: true

# åŠ¨æ•ˆ
dynamicEffect:
  postTopWave: true # æ–‡ç« é¡¶éƒ¨æ³¢æµªæ•ˆæœ
  postTopRollZoomInfo: true # æ–‡ç« é¡¶éƒ¨æ»šåŠ¨æ—¶ç¼©æ”¾
  pageCommentsRollZoom: true # éæ–‡ç« é¡µé¢è¯„è®ºæ»šåŠ¨æ—¶ç¼©æ”¾æ˜¾ç¤ºï¼ˆä»…ä»…Twikooç”Ÿæ•ˆï¼‰

# é¦–é¡µæ–‡ç« ç¼©ç•¥å›¾
cover:
  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« å°é¢
  index_enable: true
  aside_enable: true
  archives_enable: true
  # å°é¢æ˜¾ç¤ºçš„ä½ç½®
  # ä¸‰ä¸ªå€¼å¯é…ç½® left , right , both
  position: left
  # å½“æ²¡æœ‰è®¾ç½®coveræ—¶ï¼Œé»˜è®¤çš„å°é¢æ˜¾ç¤º
  default_cover: /img/run-img/3.webp

# aside (ä¾§è¾¹æ )
# --------------------------------------

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display: # æ§åˆ¶å¯¹åº”è¯¦æƒ…é¡µé¢æ˜¯å¦æ˜¾ç¤ºä¾§è¾¹æ  # ç‰¹åˆ«æ³¨æ„è¿™é‡Œçš„ä¼˜å…ˆçº§ä¸åŠ md è®¾ç½®
    archive: false # æ€»è§ˆï¼ˆä»…æ­¤é¡¹ç”Ÿæ•ˆï¼‰
    category: false # åˆ†ç±»
    tag: false # æ ‡ç­¾
  card_author:
    enable: true
    description: <div style="line-height:1.38;margin:0.6rem 0;text-align:justify;color:rgba(255, 255, 255, 0.8);">ä¸€ä¸ª<b style="color:#fff">é—²å¾—è›‹ç–¼çš„ã€çˆ±å¥½å‰ç«¯çš„ã€æŠ˜è…¾ä¸æ­¢çš„</b>ä¸šä½™å¼€å‘è€…ã€‚</div><div style="line-height:1.38;margin:0.6rem 0;text-align:justify;color:rgba(255, 255, 255, 0.8);">äººç”Ÿå°±åƒä¸€è‰˜å°èˆ¹ï¼Œå†…å¿ƒæŒ‡å¼•æ–¹å‘ã€‚</div>
    name_link: /about
  card_announcement:
    enable: false
    content: æ¬¢è¿æ¥çœ‹æˆ‘çš„åšå®¢é¸­~
  card_weixin:
    enable: true
    face: /img/WX-1.webp
    backFace: /img/WX.png
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: false
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
    highlightTags:
      - Hexo
      - å‰ç«¯
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: false
    sort_order: # Don't modify the setting unless you know how it works

# é¦–é¡µé¡¶éƒ¨ç›¸å…³é…ç½®
home_top:
  enable: true # å¼€å…³
  timemode: date #date/updated
  title: äº‹äº‹é¡ºå¿ƒ
  subTitle: å¤©å¤©å¼€å¿ƒã€‚
  siteText: YANGJIE.SITE
  category:
    - name: æ‚è®°
      path: /categories/æ‚è®°/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-book-open
    - name: ç›¸å†Œ
      path: /album/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-images
    - name: æ—¶å…‰æœº
      path: /essay/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-pencil
  default_descr: å†æ€ä¹ˆçœ‹æˆ‘ä¹Ÿä¸çŸ¥é“æ€ä¹ˆæè¿°å®ƒçš„å•¦ï¼
  swiper:
    enable: false
    swiper_css: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.css #swiper cssä¾èµ–
    swiper_js: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.js #swiper jsä¾èµ–
  banner:
    tips: XIAOJIE'NAV
    title: å°æ°å¯¼èˆªï¼Œè‡ªå¨±è‡ªä¹ğŸ˜‚ğŸ¤£ğŸ˜
    image: /img/default_cover.jpg
    link: https://nav.yangjie.site/

icons:
  ali_iconfont_js: # é˜¿é‡Œå›¾æ ‡symbol å¼•ç”¨é“¾æ¥ï¼Œä¸»é¢˜ä¼šè¿›è¡ŒåŠ è½½ symbol å¼•ç”¨
  fontawesome: false # æ˜¯å¦å¯ç”¨fontawesome6å›¾æ ‡
  fontawesome_animation_css: # fontawesome_animation å¦‚æœæœ‰å°±ä¼šåŠ è½½ï¼Œç¤ºä¾‹å€¼ï¼šhttps://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@1.0.17/lib/assets/font-awesome-animation.min.css

# åŠ è½½é¡µé¢
preloader:
  avatar: /img/avatar.jpg # è‡ªå®šä¹‰å¤´åƒ

# ç»Ÿè®¡
# 51aç»Ÿè®¡é…ç½®
LA:
  enable: true
  ck: 3HY4Mdy2v6ZYoQsr
  LingQueMonitorID: 3HY4g0VZjlJEUQe6

# å·¦ä¸‹è§’éŸ³ä¹é…ç½®é¡¹
# https://github.com/metowolf/MetingJS
nav_music:
  enable: true
  console_widescreen_music: false # å®½å±çŠ¶æ€æ§åˆ¶å°æ˜¾ç¤ºéŸ³ä¹è€Œä¸æ˜¯æ ‡ç­¾ enableä¸ºtrue æ§åˆ¶å°ä¾ç„¶ä¼šæ˜¾ç¤º
  id: 7118022387
  server: netease
  all_playlist: https://music.163.com/#/playlist?id=7118022387

theme_color:
  enable: true
  main: "#1296db"
  dark_main: "#1296db"
  paginator: "#425AEF"
  #   button_hover: "#FF7242"
  text_selection: "#2128bd"
  link_color: "var(--anzhiyu-fontcolor)"
  meta_color: "var(--anzhiyu-fontcolor)"
  hr_color: "#4259ef23"
  code_foreground: "#fff"
  code_background: "var(--anzhiyu-code-stress)"
  toc_color: "#425AEF"
  #   blockquote_padding_color: "#425AEF"
  #   blockquote_background_color: "#425AEF"
  scrollbar_color: "var(--anzhiyu-scrollbar)"
  meta_theme_color_light: "#f7f9fe"
  meta_theme_color_dark: "#18171d"

# ptool æ–‡ç« åº•éƒ¨å·¥å…·
ptool:
  enable: true
  share_mobile: true
  share_weibo: false
  share_copyurl: true
  categories: false # æ˜¯å¦æ˜¾ç¤ºåˆ†ç±»

# æœ¬åœ°æœç´¢
local_search:
  enable: true
  preload: true
  CDN:

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: true
  startup_image_enable: true
  manifest: /manifest.json
  theme_color: var(--anzhiyu-main)
  mask_icon: /img/siteicon/apple-icon-180.png
  apple_touch_icon: /img/siteicon/apple-icon-180.png
  bookmark_icon: /img/siteicon/apple-icon-180.png
  favicon_32_32: /img/siteicon/32.png
  favicon_16_16: /img/siteicon/16.png

# è¯„è®º
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Valine/Waline/Twikoo/
  use: Twikoo # Twikoo/Waline
  text: false # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: true # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://twikoo.jie-ipv6.cn:6688/
  region:
  visitor: false
  option: